### ISSUE TITLE
Make hardcoded references to Lightbend for ReadinessLevel configurable

### ISSUE THREAD

**Issue by mdedetrich** [lightbend/sbt-paradox-project-info#17]
I am currently integrating documentation in my project using sbt-paradox and following alpakka's https://doc.akka.io/docs/alpakka/current/index.html documentation as a rough guide and I ended up using sbt-paradox-project-info. When integrating sbt-paradox-project-info when using `levels` (which is currently a mandatory setting) I noticed that the generated documentation includes hardocded links to lightbends website (i.e. https://developer.lightbend.com/docs/introduction/#community-driven).

Obviously in my case I don't want my project to reference lightbend since it has nothing to do with lightbend but currently that configuration is hardcoded here https://github.com/lightbend/sbt-paradox-project-info/blob/65c5213c362a8af368267e769f8ed7b76a98d275/src/main/scala/com/lightbend/paradox/projectinfo/model.scala#L36-L68.

Ideally the actual values for `ReadinessLevel` should be configured either in `build.sbt` or the `project/project-info.conf` and by default they shouldn't have any reference to lightbend. I guess specifically in lightbend/akkas case you can then create a `sbt-lightbend-paradox` plugin which includes `sbt-paradox-project-info` and sets the various lightbend related values there. https://github.com/akka/akka-paradox is another option to use however my impressions is that project is specifically for the praadox theme

**Comment by ennru** [comment]
Great that you find this structured way to have standardised project information useful.

I guess the simplest solution would be to change the readiness level to optional. That wouldn't change anything for the current use in our Akka projects.

**Comment by mdedetrich** [comment]
@ennru Way ahead of you https://github.com/lightbend/sbt-paradox-project-info/pull/18

I still think that design wise it should be configurable but for our use case making it optional would at least unblock us from using sbt-paradox-project-info
